# 服务基本配置
server:
  port: 9024
  servlet:
    context-path: /makefriends
  tomcat:
    uri-encoding: UTF-8
spring:
  # 响应编码以及静态资源访问配置
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  http:
    encoding:
      force-response: true
  # 数据库相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/make_friends?serverTimezone=Hongkong&useUnicode= true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&nullNamePatternMatchesAll=true
    username: root
    password: foreverYsm1996
  jpa:
    show-sql: true
    database: mysql